name: Test UUID Module

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install maturin
      run: pip install maturin

    - name: Build UUID module
      env:
        PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
      run: |
        echo "Building UUID module..."
        maturin build --verbose

    - name: Test UUID functionality
      run: |
        # Install the built wheel
        echo "Installing UUID wheel..."
        pip install target/wheels/*.whl
        
        # Test basic import
        echo "Testing UUID import..."
        python -c "import rusthonian_uuid; print('UUID module imported successfully')"
        
        # Test UUID class
        echo "Testing UUID class..."
        python -c "from rusthonian_uuid import UUID; print('UUID class imported successfully')"
        
        # Test new_v4 function
        echo "Testing new_v4 function..."
        python -c "from rusthonian_uuid import new_v4; uuid = new_v4(); print(f'Generated UUID: {uuid}')"
        
        # Test UUID creation from string
        echo "Testing UUID creation from string..."
        python -c "from rusthonian_uuid import UUID; uuid = UUID('550e8400-e29b-41d4-a716-446655440000'); print(f'Created UUID: {uuid}')"
        
        # Test UUID methods
        echo "Testing UUID methods..."
        python -c "from rusthonian_uuid import new_v4; uuid = new_v4(); print(f'Bytes: {uuid.bytes()}'); print(f'As u128: {uuid.as_u128()}')"
        
        # Test utility functions
        echo "Testing utility functions..."
        python -c "from rusthonian_uuid import is_valid; print(f'Valid UUID: {is_valid(\"550e8400-e29b-41d4-a716-446655440000\")}')"
        python -c "from rusthonian_uuid import nil; print(f'Nil UUID: {nil()}')"
